name: Testing

on:
  push:
    branches: [development]

env:
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "ms1553b-%p-%m.profraw"

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Install gcovr
      run: |
        rustup component add llvm-tools-preview &&
        cargo install grcov

    - name: Build the library
      run: cargo test --no-run

    - name: Test the library
      run: cargo test

    - name: Generate code coverage
      run: grcov . -s . -b target/debug -t html --branch --ignore-not-existing --keep-only 'src/**/*' -o .

    - name: Archive code coverage
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: ./html/*

  merge:

    name: Merge
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}