name: Validate

on: pull_request

jobs:

  test:

    name: Test

    strategy:
      fail-fast: false
      matrix:
        system:
          - name: Windows - X86_64
            os: windows-latest
            target: x86_64-unknown-linux-gnu
            toolchain: x86_64-pc-windows-gnu

        # os:
        #   - windows-latest 
        #   # - ubuntu-latest 
        #   # - macos-latest
        # target:
        #   - x86_64-unknown-linux-gnu

        #   # - aarch64-unknown-linux-gnu
        #   # - armv7-unknown-linux-gnueabi
        #   # - i686-unknown-linux-gnu

    runs-on: ${{ matrix.system.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: |
        rustup update --no-self-update stable &&
        rustup target add ${{ matrix.system.target }} &&
        rustup toolchain install ${{ matrix.system.toolchain }} &&
        rustup default ${{ matrix.system.toolchain }}

    - name: Test the library
      run: |
        cargo test --target ${{ matrix.target }}

  coverage:
    needs: test

    env:
      RUSTFLAGS: "-C instrument-coverage"
      LLVM_PROFILE_FILE: "ms1553b-%p-%m.profraw"

    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Install grcov
      run: |
        rustup component add llvm-tools-preview &&
        cargo install grcov

    - name: Build the library
      run: cargo test --no-run

    - name: Test the library
      run: cargo test

    - name: Generate code coverage
      run: grcov . -s . -b target/debug -t cobertura --branch --ignore-not-existing --keep-only 'src/**/*' -o .

    - name: Make coverage report
      uses: 5monkeys/cobertura-action@v13
      with: 
        path: ./cobertura.xml
        report_name: Coverage
        skip_covered: false
        only_changed_files: false
        fail_below_threshold: true
        minimum_coverage: 95