name: Validate

on: pull_request

env:
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "ms1553b-%p-%m.profraw"

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Install gcovr
      run: |
        rustup component add llvm-tools-preview &&
        cargo install grcov

    - name: Build the library
      run: cargo build --verbose
    
    - name: Test the library
      run: cargo test --verbose

    - name: Generate code coverage
      run: |
        mkdir -p ./target/debug/coverage && 
        grcov . -s . -b ./target/debug/ -t cobertura --branch --ignore-not-existing -o .

    - name: Code Coverage Report Action
      uses: insightsengineering/coverage-action@v2.6.0
      with:
        path: ./cobertura.xml
        threshold: 80
        fail: true
        publish: true
        diff: false
        coverage-summary-title: "Coverage"