name: Validate

on: pull_request

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Install grcov
      run: |
        rustup component add llvm-tools-preview &&
        cargo install grcov

    - name: Build the library
      run: cargo build --tests

    - name: Test the library
      env:
        RUSTFLAGS: "-C instrument-coverage"
        LLVM_PROFILE_FILE: "ms1553b-%p-%m.profraw"
      run: cargo test

    - name: Generate code coverage
      run: grcov . -s . -b ./target/debug/ -t cobertura --branch --ignore-not-existing -o .

    - name: Make coverage report
      uses: 5monkeys/cobertura-action@v13
      with: 
        path: ./cobertura.xml
        fail_below_threshold: true
        minimum_coverage: 95

      # uses: insightsengineering/coverage-action@v2.6.0
      # with:
      #   path: ./cobertura.xml
      #   threshold: 95
      #   fail: true